global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "doc-pipeline"
    static_configs:
      - targets: ["app:8080"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
